### ISSUE TITLE
How do I run the app?

### ISSUE THREAD

**Issue by AllanLRH** [patrickmoffitt/python-example#1]
Being completely new to JS technologies, how do I run this app (using OS X and Linux)?
Do I have to install Electron? The _package.json_ seems to suggest an app-version of Electron.

**Comment by AllanLRH** [comment]
Nevermind, figured it out.
From the root of the repository, run `node_modules/.bin/electron .`

**Comment by patrickmoffitt** [comment]
Your intuition is correct. To run the example:

1. Visit [https://electron.atom.io/releases/](https://electron.atom.io/releases/) and select the latest release.
2. Download and install Electron for your platform.
3. Open a shell and navigate to the folder where you unpacked the example.
4. Run /path-to-electron/electon .

The last command passes the current working directory to electron as an argument. Make sure to replace path-to-electron with your own local path.
